MAX_STEPS: null


KINECT2:
  DEPTH:
    HEIGHT: 424
    WIDTH: 512
    DISTANCE: 1.0
    INTRINSICS: [372.66, 0., 241.20, 0., 368.62, 214.19, 0., 0., 1.]
    TRANSLATION: [0, -0.60, 1.5]
    ROTATION: [-3.1415, 0, 1.5708]
    INTRINSICS_NOISE: null
    TRANSLATION_NOISE: null
    ROTATION_NOISE: null
    CROP: [150, 20, 350, 250]


ARM:
  # Move the arm out of the table.
  OFFSTAGE_POSITIONS: [-1.5, -1.26, 0.00, 1.98, 0.00, 0.85, 3.3161]

  # Move the arm above the table.
  OVERHEAD_POSITIONS: [-0.73, -1.13, 0.82, 1.51, -0.33, 1.34, 1.87]

  # The safe height to move the gripper above the table.
  GRIPPER_SAFE_HEIGHT: 0.4

  # The distance from the the end effector to the center of finger tips.
  FINGER_TIP_OFFSET: 0.125

  # If move to the overhead position after grasping.
  MOVE_TO_OVERHEAD_AFTER_GRASP: 0


TABLE:
  HEIGHT_RANGE: [0.8, 0.8]
  X_RANGE: 0.76
  Y_RANGE: 1.22


SIM:
  ARM:
    CONFIG: null
    POSE: [[0, 0, 0], [0, 0, 0]]

  GROUND:
    PATH: 'sim/envs/arm_env/planes/plane_ceramic.urdf'
    POSE: [[0, 0, -0.9], [0, 0, 0]]

  WALL:
    USE: 0
    PATH: 'sim/envs/arm_env/wall.urdf'
    POSE: [[0, 0, -0.9], [0, 0, 0]]

  TABLE:
      PATH: 'sim/envs/arm_env/tables/table_svl_wooden.urdf'
      POSE: [[0.6, 0.05, -0.9], [0, 0, 0]]
      HEIGHT_RANGE: [0.8, 0.8]
      X_RANGE: 0.76
      Y_RANGE: 1.22
