!include configs/envs/arm_env.yaml

DEBUG: 0

MAX_STEPS: null

OBSERVATION:
  # Choose between `depth` and `point_cloud`.
  TYPE: 'depth'

ACTION:
  # Choose between `IMAGE`(in image space) and `CUBOID`(in a 3D cuboid region).
  TYPE: 'IMAGE'

  # The `CUBOID` defines a cuvoid region for the grasping center.
  CUBOID:
    LOW: [0.30, -0.50, 0.02]
    HIGH: [0.90, 0.50, 0.12]


SIM:
  ARM:
    CONFIG: null
    POSE: [[0, 0, 0], [0, 0, 0]]

  GROUND:
    PATH: 'sim/envs/arm_env/planes/plane.urdf'
    POSE: [[0, 0, -0.9], [0, 0, 0]]

  WALL:
    USE: 0
    PATH: 'sim/envs/arm_env/wall.urdf'
    POSE: [[0, 0, -0.9], [0, 0, 0]]

  TABLE:
      PATH: 'sim/envs/arm_env/tables/table_grasp.urdf'
      POSE: [[0.6, 0, -0.9], [0, 0, 0]]
      HEIGHT_RANGE: [0.9, 0.9]

  GRASPABLE:
    PATHS: [
    'sim/procedural/*0/*.urdf',
    ]
    POSE:
      X: [-0.15, 0.15]
      Y: [-0.15, 0.15]
      Z: 0.3
      ROLL: [-3.14, 3.14]
      PITCH: [-1.57, 1.57]
      YAW: [-3.14, 3.14]
    SCALE: [0.8, 1.2]
    USE_RANDOM_SAMPLE: 1
    RESAMPLE_N_EPISODES: 1

  MAX_ACTION_STEPS: 4000
