!include configs/envs/arm_env.yaml


DEBUG: 1


TASK_NAME: null
LAYOUT_ID: 0


MAX_STEPS: 20
NUM_GOAL_STEPS: null


MOVABLE_NAME: 'YCB'
USE_RANDOM_RGBA: 0
MIN_MOVABLE_BODIES: 3
MAX_MOVABLE_BODIES: 5


MAX_STATE_PLOTS: 1
MAX_ACTION_PLOTS: 16
NUM_INFO_SAMPLES: 1024


USE_VISUALIZATION_OBS: 0
USE_PRESTIGE_OBS: 1


SUCCESS_THRESH: 0.5


ACTION:
  CSPACE:
    LOW: [0.3, -0.55, 0.045]
    HIGH: [0.8, 0.55, 0.045]

  MOTION:
    TRANSLATION_X: 0.1
    TRANSLATION_Y: 0.1

  MIN_DELTA_POSITION: 0.01
  MIN_DELTA_ANGLE: 0.01


OBS:
  NUM_POINTS: 256
  CROP_MIN: [0.25, -0.525, -0.2]
  CROP_MAX: [0.95, 0.575, 0.2]


TASK: 
  CLEARING:
    LAYOUT_NAMES: [
      'CLEARING_01',
      'CLEARING_02',
      'CLEARING_03',
    ]

  INSERTION:
    LAYOUT_NAMES: [
      'INSERTION_01',
      'INSERTION_02',
      'INSERTION_03',
    ]

  CROSSING:
    LAYOUT_NAMES: [
      'CROSSING_01',
      'CROSSING_02',
      'CROSSING_03',
    ]


KINECT2:
  DEPTH:
    HEIGHT: 424
    WIDTH: 512
    DISTANCE: 1.0
    INTRINSICS: [350, 0, 250, 0, 345, 230, 0, 0, 1]
    TRANSLATION: [-0.026653883444807847, -0.6578901567634426, 0.8304315827193013]
    ROTATION: [-3.1415, 0, 1.5708]
    INTRINSICS_NOISE: null
    TRANSLATION_NOISE: null
    ROTATION_NOISE: null

  RGB:
    HEIGHT: 1080
    WIDTH: 1920
    DISTANCE: 1.0
    INTRINSICS: [1032.74, 0, 956.86, 0, 1032.34, 539.14, 0, 0, 1]
    TRANSLATION: [-0.026653883444807847, -0.6578901567634426, 0.8304315827193013]
    ROTATION: [-3.1415, 0, 1.5708]
    INTRINSICS_NOISE: null
    TRANSLATION_NOISE: null
    ROTATION_NOISE: null


TABLE:
  HEIGHT_RANGE: [0.8, 0.8]
  X_RANGE: 0.76
  Y_RANGE: 1.22


SIM:
  MAX_PHASE_STEPS: 2000
  MAX_MOTION_STEPS: 2000
  MAX_OFFSTAGE_STEPS: 5000
  STEPS_CHECK: 100

  ARM:
    CONFIG: 'configs/robots/sawyer_sim_with_stick.yaml'
    POSE: [[0, 0, 0], [0, 0, 0]]

  GROUND:
    PATH: 'sim/envs/arm_env/planes/plane_ceramic.urdf'
    POSE: [[0, 0, -0.9], [0, 0, 0]]

  WALL:
    USE: 0
    PATH: 'sim/envs/arm_env/wall.urdf'
    POSE: [[0, 0, -0.9], [0, 0, 0]]

  TABLE:
    PATH: 'sim/envs/arm_env/tables/table_svl_wooden.urdf'
    POSE: [[0.6, 0.05, -0.9], [0, 0, 0]]

  FENCE:
    PATH: 'sim/envs/push_env/fence_svl_wooden.urdf'

  TILE:
    PATH: 'sim/envs/push_env/tile.urdf'


MOVABLE:
  CYLINDER:
    PATHS: [
      'sim/envs/push_env/cylinder_large_r.urdf',
    ]
    TARGET_PATHS: [
      'sim/envs/push_env/cylinder_large_r.urdf',
    ]
    POSE:
      X: [0.4, 0.7]
      Y: [-0.4, 0.4]
      Z: 0.2
      ROLL: [0, 0]
      PITCH: [0, 0]
      YAW: [0, 3.14]
    SCALE:
      [1.5, 1.5]
    MARGIN: 0.15
    MASS: 0.5
    FRICTION: 0.8

  YCB:
    PATHS: [
      'sim/ycb_svl/*/*/*.urdf',
    ]
    TARGET_PATHS: [
      'sim/ycb_svl/025_mug/*/*.urdf',
    ]
    POSE:
      X: [0.4, 0.7]
      Y: [-0.4, 0.4]
      Z: 0.2
      ROLL: [-3.14, 3.14]
      PITCH: [0, 3.14]
      YAW: [-3.14, 3.14]
    SCALE:
      [0.8, 1.2]
    MARGIN: 0.15
    MASS: 10.
    FRICTION: 0.8

  MPI:
    PATHS: [
      'sim/mpi_filtered/*/*.urdf',
    ]
    TARGET_PATHS: [
      'sim/mpi_filtered/*/*.urdf',
    ]
    POSE:
      X: [0.4, 0.7]
      Y: [-0.4, 0.4]
      Z: 0.2
      ROLL: [-3.14, 3.14]
      PITCH: [0, 3.14]
      YAW: [-3.14, 3.14]
    SCALE:
      [1.0, 1.0]
    MARGIN: 0.15
    MASS: 100.
    FRICTION: 1.0


RECORDING:
  USE: 0
  OUTPUT_DIR: 'episodes/recording'
  NUM_STEPS: 200
  FPS: 30

  CAMERA:
    HEIGHT: 1080
    WIDTH: 1920
    INTRINSICS: [1032.74, 0, 956.86, 0, 1032.34, 539.14, 0, 0, 1]
    TRANSLATION: [-0.050, -0.054, 1.680]
    ROTATION: [-3.1416, 1.1416, 1.5708]
