# Data collection for PushEnv.
!include configs/envs/push_env.yaml

DEBUG: 0


MIN_MOVABLE_BODIES: 3
MAX_MOVABLE_BODIES: 5


MAX_STEPS: 5
MOVABLE_NAME: 'YCB'
USE_RANDOM_RGBA: false


KINECT2:
  DEPTH:
    HEIGHT: 424
    WIDTH: 512
    DISTANCE: 1.0
    INTRINSICS: [350, 0, 250, 0, 350, 225, 0, 0, 1]
    TRANSLATION: [-0.026653883444807847, -0.6578901567634426, 0.8304315827193013]
    ROTATION: [-3.1415, 0, 1.5708]
    INTRINSICS_NOISE: [15, 0, 15, 0, 15, 15, 0, 0, 0]
    TRANSLATION_NOISE: [0.05, 0.05, 0.05]
    ROTATION_NOISE: [0.025, 0.025, 0.025]
    CROP: null
