!include configs/robots/sawyer.yaml


# Default maximum joint velocity ratio, chosen from (0, 1].
# Set it to 1.0 for data collection, 0.3 for demo.
LIMB_MAX_VELOCITY_RATIO: 1.0

# Path to the URDF file of the arm(without base, with gripper).
ARM_URDF: 'robots/rethink/sawyer_description/urdf/sawyer_arm.urdf'

# Path to the URDF file of the base.
BASE_URDF: 'robots/rethink/sawyer_description/urdf/sawyer_base.urdf'

# Path to the URDF file of the head.
HEAD_URDF: 'robots/rethink/sawyer_description/urdf/sawyer_head.urdf'
