#
# Robot parts.
#

# Joint indices of the limb.
LIMB_JOINT_NAMES: [
  'right_j0',
  'right_j1',
  'right_j2',
  'right_j3',
  'right_j4',
  'right_j5',
  'right_j6',
  ]

# Link name of the end effector, for computing IK.
END_EFFCTOR_NAME: 'right_hand'

# Joint name of the left finger of the gripper.
L_FINGER_NAME: 'r_gripper_l_finger_joint'

# Joint name of the right finger of the gripper.
R_FINGER_NAME: 'r_gripper_r_finger_joint'

# Link name of the left finger tip of the gripper.
L_FINGER_TIP_NAME: 'r_gripper_l_finger_tip'

# Link name of the right finger tip of the gripper.
R_FINGER_TIP_NAME: 'r_gripper_r_finger_tip'

# Open the gripper when resetting the robot.
OPEN_GRIPPER_WHEN_RESET: false


#
# Control constants.
#

# Default maximum time (in seconds) for position control.
LIMB_TIMEOUT: 15.0

# Neutral and default initial joint position of the limb.
LIMB_NEUTRAL_POSITIONS: [
  0,
  -1.18,
  0.00,
  2.18,
  0.00,
  0.57,
  3.3161,
  ]

# Maximum joint velocities of the limb.
LIMB_MAX_VELOCITIES: [
  1.740,
  1.328,
  1.957,
  1.957,
  3.485,
  3.485,
  4.545,
  ]

# Default maximum joint velocity ratio, chosen from (0, 1].
# Set it to 1.0 for data collection, 0.3 for demo.
LIMB_MAX_VELOCITY_RATIO: 0.3

# Threshold (in rads) for each joint for position control.
LIMB_POSITION_THRESHOLD: 0.008726640

# Height of the limb (installed on the base) from the ground, for computing IK.
LIMB_HEIGHT: 0.9

# Step size of a gripper trajectory.
END_EFFECTOR_STEP: 0.001

# Motion planning package.
# MOTION_PLANNING: 'moveit'
MOTION_PLANNING: null


#
# URDF.
#

# Path to the URDF file of the arm(without base, with gripper).
ARM_URDF: 'robots/rethink/sawyer_description/urdf/sawyer.urdf'

# Path to the URDF file of the base.
BASE_URDF: null

# Path to the URDF file of the head.
HEAD_URDF: null
