DEBUG: 1
BATCHED: 1
HEURISTICS: null


NUM_INFO_SAMPLES: 1024


# Task.
TASK_NAME: null
LAYOUT_ID: null


# Network.
USE_RELATION: true
USE_POINT_CLOUD: true
USE_POINT_CLOUD_CENTER: true

REWARD_THRESH: 0.0
REWARD_THRESH_HIGH: 0.0

POSITION_NOISE: 0.2

DELTA_STATE_POSITION_RANGE: 0.15
DELTA_GOAL_POSITION_RANGE: 0.5


DIM_C: 16
DIM_Z: 16

DIM_FC_C: 64
DIM_FC_Z: 64
DIM_FC_STATE: 64
DIM_FC_ACTION: 64


# Training.
STATE_LOSS_WEIGHT: 1000.
ENCODING_LOSS_WEIGHT: 10.
ACTION_LOSS_WEIGHT: 5.
KLD_LOSS_WEIGHT: 0.1
CFR_LOSS_WEIGHT: 0.1

USE_CFR: 0

AUGMENT_POSITION: true
AUGMENT_POINT_CLOUD: false


# Sampling.
NUM_SAMPLED_ACTIONS: 8192
NUM_SAMPLED_CS: 8192
NUM_SAMPLED_ZS: 8192

NUM_STEPS: 30
NUM_GOAL_STEPS: 3

USE_PRUNING: 1
